# Generated by Django 3.1.4 on 2021-01-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('pv_yield', models.IntegerField(blank=True, db_column='yield', null=True)),
                ('state', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Yield',
            },
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('plz', models.TextField(primary_key=True, serialize=False)),
                ('state', models.ForeignKey(blank=True, db_column='state', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='energyapp.yield')),
            ],
            options={
                'db_table': 'PostalCode',
            },
        ),
    ]
