# Generated by Django 3.1.4 on 2020-12-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('state', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('pv_yield', models.IntegerField()),
            ],
        ),
    ]
