# Generated by Django 3.1.4 on 2020-12-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yield',
            options={'managed': False},
        ),
    ]
