# Generated by Django 3.1.4 on 2020-12-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyapp', '0002_auto_20201214_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_code', models.IntegerField(blank=True, null=True)),
                ('max_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PostalCode',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='yield',
            table='Yield',
        ),
    ]
