# Generated by Django 3.1.4 on 2020-12-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energyapp', '0003_auto_20201214_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postalcode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='yield',
            options={},
        ),
    ]
